"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommonTab = void 0;
const React = require("react");
const SymbolDraftContext_1 = require("../SymbolDraftContext");
function CommonTab() {
    const { draft, setDraft } = (0, SymbolDraftContext_1.useSymbolDraft)();
    const updateField = (field, val) => {
        setDraft(prev => ({ ...prev, [field]: val }));
    };
    return (React.createElement("div", { style: { display: 'flex', flexDirection: 'column', height: '100%', gap: 10, fontSize: 11 } },
        React.createElement("div", { style: { display: 'flex', gap: 12, alignItems: 'center', background: 'var(--theia-sideBarSectionHeader-background)', padding: '6px 12px', borderRadius: 4 } },
            React.createElement("div", { style: { width: 32, height: 32, display: 'flex', justifyContent: 'center', alignItems: 'center', background: '#f39c12', borderRadius: 4, color: '#fff', fontSize: 18, fontWeight: 'bold' } }, "$"),
            React.createElement("div", { style: { flex: 1, opacity: 0.9, lineHeight: 1.3 } }, "The setting up of main parameters of the symbol. Please specify its name, description, and other parameters.")),
        React.createElement("div", { style: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px 24px' } },
            React.createElement("div", { style: { display: 'flex', flexDirection: 'column', gap: 6 } },
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Symbol:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, required: true, value: draft.symbol, onChange: e => updateField('symbol', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Exchange:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.exchange, onChange: e => updateField('exchange', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "ISIN:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.isin, onChange: e => updateField('isin', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "CFI:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.cfi, onChange: e => updateField('cfi', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Basis:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.basis, onChange: e => updateField('basis', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Source:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.quote_source, onChange: e => updateField('quote_source', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Background:"),
                    React.createElement("div", { style: { flex: 1, display: 'flex', gap: 6, alignItems: 'center' } },
                        React.createElement("input", { type: "color", style: { width: 30, height: 20, border: 'none', cursor: 'pointer', padding: 0 }, value: draft.bg_color, onChange: e => updateField('bg_color', e.target.value) }),
                        React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.bg_color, onChange: e => updateField('bg_color', e.target.value) }))),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Digits:"),
                    React.createElement("select", { className: "adm-select", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.digits, onChange: e => updateField('digits', parseInt(e.target.value) || 0) },
                        React.createElement("option", { value: 0 }, "0"),
                        React.createElement("option", { value: 1 }, "1"),
                        React.createElement("option", { value: 2 }, "2"),
                        React.createElement("option", { value: 3 }, "3"),
                        React.createElement("option", { value: 4 }, "4"),
                        React.createElement("option", { value: 5 }, "5"))),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Spread:"),
                    React.createElement("div", { style: { flex: 1, display: 'flex', gap: 6, alignItems: 'center' } },
                        React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, type: "number", value: draft.fixed_spread, onChange: e => updateField('fixed_spread', parseInt(e.target.value) || 0) }),
                        React.createElement("span", null, "pt")))),
            React.createElement("div", { style: { display: 'flex', flexDirection: 'column', gap: 6 } },
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Description:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.description, onChange: e => updateField('description', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "International:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.intl_name, onChange: e => updateField('intl_name', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Sector:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.sector, onChange: e => updateField('sector', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Industry:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.industry, onChange: e => updateField('industry', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Country:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.country, onChange: e => updateField('country', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Category:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.category, onChange: e => updateField('category', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Page:"),
                    React.createElement("input", { className: "adm-input", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.info_page, onChange: e => updateField('info_page', e.target.value) })),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Market depth:"),
                    React.createElement("select", { className: "adm-select", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.market_depth, onChange: e => updateField('market_depth', parseInt(e.target.value) || 0) },
                        React.createElement("option", { value: 0 }, "off"),
                        React.createElement("option", { value: 5 }, "5"),
                        React.createElement("option", { value: 10 }, "10"),
                        React.createElement("option", { value: 20 }, "20"),
                        React.createElement("option", { value: 32 }, "32"))),
                React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8 } },
                    React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Chart mode:"),
                    React.createElement("select", { className: "adm-select", style: { flex: 1, height: 20, padding: '2px 6px', fontSize: 11 }, value: draft.chart_mode, onChange: e => updateField('chart_mode', e.target.value) },
                        React.createElement("option", { value: "bid" }, "by bid price"),
                        React.createElement("option", { value: "last" }, "by last price"))))),
        React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8, marginTop: 4 } },
            React.createElement("span", { style: { width: 80, textAlign: 'right', opacity: 0.8 } }, "Spread balance:"),
            React.createElement("div", { style: { flex: 1, display: 'flex', alignItems: 'center', gap: 10 } },
                React.createElement("input", { type: "range", min: "-100", max: "100", style: { flex: 1, cursor: 'pointer', height: 16 }, value: draft.spread_balance_bid, onChange: e => {
                        const val = parseInt(e.target.value) || 0;
                        updateField('spread_balance_bid', val);
                        updateField('spread_balance_ask', -val);
                    } }),
                React.createElement("span", { style: { width: 100, fontSize: 11 } },
                    draft.spread_balance_bid,
                    " bid / ",
                    draft.spread_balance_ask,
                    " ask")))));
}
exports.CommonTab = CommonTab;
//# sourceMappingURL=CommonTab.js.map