"""010_sync_schema

Revision ID: c8f8333980f2
Revises: 009_identity_plane
Create Date: 2026-09-28 19:30:12.980624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '010_sync_schema'
down_revision = '009_identity_plane'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_breaks',
    sa.Column('break_id', sa.String(length=64), nullable=False),
    sa.Column('identity', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('our_key', sa.String(length=128), nullable=True),
    sa.Column('venue_key', sa.String(length=128), nullable=True),
    sa.Column('our_volume', sa.Numeric(), nullable=True),
    sa.Column('venue_volume', sa.Numeric(), nullable=True),
    sa.Column('our_price', sa.Numeric(), nullable=True),
    sa.Column('venue_price', sa.Numeric(), nullable=True),
    sa.Column('account_login', sa.BigInteger(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('break_id')
    )
    op.create_index('ix_recon_breaks_status', 'reconciliation_breaks', ['status', 'severity'], unique=False)
    op.create_index('ix_recon_breaks_symbol', 'reconciliation_breaks', ['symbol'], unique=False)
    op.create_index(op.f('ix_reconciliation_breaks_identity'), 'reconciliation_breaks', ['identity'], unique=False)
    op.create_foreign_key(None, 'managers', 'groups', ['group_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'managers', type_='foreignkey')
    op.drop_index(op.f('ix_reconciliation_breaks_identity'), table_name='reconciliation_breaks')
    op.drop_index('ix_recon_breaks_symbol', table_name='reconciliation_breaks')
    op.drop_index('ix_recon_breaks_status', table_name='reconciliation_breaks')
    op.drop_table('reconciliation_breaks')
    # ### end Alembic commands ###
