import * as React from 'react';
export interface SymbolDraft {
    symbol: string;
    digits: number;
    contract_size: number;
    currency: string;
    margin_initial: number;
    margin_maintenance: number;
    spread_base: number;
    session_hours: string;
    description: string;
    isin: string;
    intl_name: string;
    exchange: string;
    category: string;
    cfi: string;
    sector: string;
    industry: string;
    country: string;
    basis: string;
    info_page: string;
    quote_source: string;
    bg_color: string;
    market_depth: number;
    fixed_spread: number;
    spread_balance_bid: number;
    spread_balance_ask: number;
    chart_mode: 'bid' | 'last';
    base_currency: string;
    profit_currency: string;
    margin_currency: string;
    allow_realtime_quotes: boolean;
    allow_negative_prices: boolean;
    save_raw_prices: boolean;
    receive_market_stats: boolean;
    soft_filter_level: number;
    soft_filter_repeats: number;
    hard_filter_level: number;
    hard_filter_repeats: number;
    discard_filter_level: number;
    min_spread: number;
    max_spread: number;
    gap_mode_level: number;
    gap_disable_ticks: number;
    delay_subscriptions: number;
    calculation: string;
    trade_mode: 'disabled' | 'long_only' | 'short_only' | 'close_only' | 'full';
    gtc_mode: number;
    limit_stop_level: number;
    freeze_level: number;
    max_quote_delay: number;
    expiration_flags: string[];
    orders_allowed: string[];
    min_volume: number;
    max_volume: number;
    step_volume: number;
    limit_volume: number;
    execution_mode: 'Instant' | 'Request' | 'Market' | 'Exchange';
    instant_max_time_dev: number;
    instant_fast_requotes: boolean;
    request_timeout: number;
    request_confirm: boolean;
    exclude_long_pnl: boolean;
    calc_hedged_larger_leg: boolean;
    recalc_margin_eod: boolean;
    check_before_execution: boolean;
    check_on_sltp: boolean;
    rate_market_buy_init: number;
    rate_market_buy_maint: number;
    rate_market_sell_init: number;
    rate_market_sell_maint: number;
    rate_limit_buy_init: number;
    rate_limit_buy_maint: number;
    rate_limit_sell_init: number;
    rate_limit_sell_maint: number;
    enable_swaps: boolean;
    swap_type: 'points' | 'money' | 'percent' | 'reopen_close' | 'reopen_bid';
    swap_long: number;
    swap_short: number;
    swap_days_in_year: number;
    swap_multipliers: Record<string, number>;
    splice_type: 'none' | 'unadjusted' | 'adjusted';
    splice_date_extension: string;
    splice_shift_days: number;
    option_type: 'call' | 'put';
    option_style: 'american' | 'european';
    strike_price: number;
    bond_face_value: number;
    bond_accrued_interest: number;
}
export declare const DEFAULT_SYMBOL_DRAFT: SymbolDraft;
export interface SymbolDraftContextType {
    draft: SymbolDraft;
    setDraft: React.Dispatch<React.SetStateAction<SymbolDraft>>;
    errors: Record<string, string>;
    setErrors: React.Dispatch<React.SetStateAction<Record<string, string>>>;
    isEditing: boolean;
}
export declare const SymbolDraftContext: React.Context<SymbolDraftContextType | undefined>;
export declare function useSymbolDraft(): SymbolDraftContextType;
//# sourceMappingURL=SymbolDraftContext.d.ts.map