"""symbols.margin_currency: the M3 model column missing from the migration chain.

M3 added CurrencyMargin modelling (root cause of the cross-currency margin bugs)
to SymbolModel, but the proofs ran on SQLite via Base.metadata.create_all, which
builds from the models - so no migration was ever generated for it. Against real
PostgreSQL the chain lagged the models by one column. Detected by M5 running
alembic autogenerate against a live Neon database; the diff was exactly this
column, which is also the proof the rest of the chain is in sync.

Revision ID: 003_symbols_margin_currency
Revises: 002_price_current_nullable
Create Date: 2026-09-10 21:00:18.822684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '003_symbols_margin_currency'
down_revision = '002_price_current_nullable'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'symbols',
        sa.Column(
            'margin_currency',
            sa.String(length=8),
            nullable=False,
            # server_default so the migration also works on a symbols table that
            # already holds rows; the model's Python-side default stays authoritative.
            server_default=sa.text("'USD'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbols', 'margin_currency')
    # ### end Alembic commands ###
