import * as React from 'react';
import { FloatingWindow } from '../../shared/FloatingWindow';
import { API, isBackendGap } from '../../services/api';

interface Props {
    initialGroup?: string;
    onClose: () => void;
    onSaved: (msg: string) => void;
    onError: (msg: string, gap?: boolean) => void;
}

interface Form {
    preferred_login: string;
    group: string;
    preferred_client: string;
    client_candidates: any[];
    name: string;
    last_name: string;
    middle_name: string;
    company: string;
    email: string;
    phone: string;
    country: string;
    state: string;
    city: string;
    zip: string;
    address: string;
    master: string;
    investor: string;
    phone_pwd: string;
}

const RULE = '4 character types (lower, UPPER, digit, symbol), min 8 / max 16. Left empty = generated by the server and shown once.';

function generatePassword(): string {
    const all = 'abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789#@!$%';
    return Array.from({ length: 12 }, () => all[Math.floor(Math.random() * all.length)]).join('');
}

/**
 * New Account dialog — a DIFFERENT window from editing (doc §Accounts/
 * Creating-Account): two boxes, Details + Passwords.
 */
export function AccountNewModal({ initialGroup, onClose, onSaved, onError }: Props): React.ReactElement {
    const [groups, setGroups] = React.useState<any[]>([]);
    const [f, setF] = React.useState<Form>({
        preferred_login: 'Next', group: initialGroup ?? '', preferred_client: '', client_candidates: [],
        name: '', last_name: '', middle_name: '', company: '', email: '', phone: '',
        country: '', state: '', city: '', zip: '', address: '',
        master: '', investor: '', phone_pwd: '',
    });
    const [saving, setSaving] = React.useState(false);
    const [searching, setSearching] = React.useState(false);

    const set = (patch: Partial<Form>) => setF((x) => ({ ...x, ...patch }));

    React.useEffect(() => {
        API.getGroups().then((g) => {
            setGroups(g);
            setF((x) => ({ ...x, group: x.group || g[0]?.name || '' }));
        }).catch(() => setGroups([]));
    }, []);

    const findClients = async () => {
        setSearching(true);
        try {
            const all = await API.getClients();
            const q = f.preferred_client.trim().toLowerCase();
            setF((x) => ({
                ...x,
                client_candidates: q
                    ? all.filter((c: any) =>
                        `${c.id} ${c.first_name} ${c.last_name} ${c.email} ${c.phone}`.toLowerCase().includes(q)).slice(0, 6)
                    : all.slice(0, 6),
            }));
        } catch (e: any) {
            if (isBackendGap(e)) setF((x) => ({ ...x, client_candidates: [] }));
            onError(String(e?.message ?? e), isBackendGap(e));
        } finally {
            setSearching(false);
        }
    };

    const submit = async (e: React.FormEvent) => {
        e.preventDefault();
        setSaving(true);
        try {
            const res = await API.createAccount({
                login: f.preferred_login && f.preferred_login !== 'Next' ? Number(f.preferred_login) : undefined,
                group_name: f.group,
                client_id: f.preferred_client || undefined,
                initial_balance: 0,
                leverage: 100,
                name: [f.name, f.last_name].filter(Boolean).join(' '),
                first_name: f.name,
                last_name: f.last_name,
                middle_name: f.middle_name,
                company: f.company,
                email: f.email,
                phone: f.phone,
                country: f.country,
                state: f.state,
                city: f.city,
                zip: f.zip,
                address: f.address,
                password: f.master || undefined,
                investor_password: f.investor || undefined,
                phone_password: f.phone_pwd || undefined,
            });
            const masterPwd = res?.master_password || res?.passwords?.master_password;
            const pwdInfo = masterPwd
                ? ` [Login: ${res?.login}, Master Password: ${masterPwd}]`
                : res?.login ? ` [Login: ${res.login}]` : '';
            onSaved(`Account created successfully!${pwdInfo}`);
        } catch (err: any) {
            onError(String(err?.message ?? err), isBackendGap(err));
        } finally {
            setSaving(false);
        }
    };

    const field = (label: string, key: keyof Form, extra: React.InputHTMLAttributes<HTMLInputElement> = {}) => (
        <div className="wb-settings-row">
            <label>{label}</label>
            <input className="adm-input" value={String(f[key] ?? '')} onChange={(e) => set({ [key]: e.target.value } as any)} {...extra} />
        </div>
    );

    return (
        <FloatingWindow width={980} height={660} onClose={onClose}>
            <form className="adm-modal ca-modal ca-modal-xl" onSubmit={submit}>
                <div className="adm-modal-header">
                    <i className="codicon codicon-add" />
                    <span>New Trading Account</span>
                    <button type="button" className="adm-icon-btn" onClick={onClose}><i className="codicon codicon-close" /></button>
                </div>
                <div className="adm-modal-body ca-modal-body">
                    <div className="ca-box">
                        <div className="ca-box-title"><i className="codicon codicon-person" /> Details</div>
                        <div className="ca-modal-grid">
                            <div className="wb-settings-row">
                                <label>Preferred Login</label>
                                <input className="adm-input" value={f.preferred_login} onChange={(e) => set({ preferred_login: e.target.value })} placeholder="Next" />
                                <div className="wb-settings-hint">“Next” = closest free number; deleted logins are never reused</div>
                            </div>
                            <div className="wb-settings-row">
                                <label>Group</label>
                                <select className="adm-select" value={f.group} onChange={(e) => set({ group: e.target.value })}>
                                    {groups.map((g) => <option key={g.name} value={g.name}>{g.name}</option>)}
                                </select>
                                <div className="wb-settings-hint">group determines the account type</div>
                            </div>
                            <div className="wb-settings-row" style={{ gridColumn: '1 / -1' }}>
                                <label>Preferred Client (existing)</label>
                                <div className="ca-clientsearch">
                                    <input
                                        className="adm-input"
                                        placeholder="ID, name, email or phone…"
                                        value={f.preferred_client}
                                        onChange={(e) => set({ preferred_client: e.target.value })}
                                    />
                                    <button type="button" className="wb-btn secondary" onClick={() => void findClients()} disabled={searching}>
                                        <i className="codicon codicon-refresh" /> Request
                                    </button>
                                </div>
                                {f.client_candidates.length > 0 && (
                                    <div className="ca-candidate-list">
                                        {f.client_candidates.map((c: any) => (
                                            <button
                                                type="button"
                                                key={c.id}
                                                className={`ca-candidate ${f.preferred_client === c.id ? 'active' : ''}`}
                                                onClick={() => set({ preferred_client: c.id })}
                                            >
                                                <code className="adm-code">{c.id}</code> {c.first_name} {c.last_name} · {c.email}
                                            </button>
                                        ))}
                                    </div>
                                )}
                            </div>
                            {field('Name', 'name')}
                            {field('Last Name', 'last_name')}
                            {field('Middle Name', 'middle_name')}
                            {field('Company', 'company')}
                            {field('E-Mail', 'email', { type: 'email' })}
                            {field('Phone', 'phone')}
                            {field('Country', 'country')}
                            {field('State', 'state')}
                            {field('City', 'city')}
                            {field('Zip code', 'zip')}
                            <div className="wb-settings-row" style={{ gridColumn: '1 / -1' }}>
                                <label>Address</label>
                                <input className="adm-input" value={f.address} onChange={(e) => set({ address: e.target.value })} />
                            </div>
                        </div>
                    </div>

                    <div className="ca-box">
                        <div className="ca-box-title"><i className="codicon codicon-key" /> Passwords</div>
                        <div className="wb-settings-hint" style={{ margin: '0 0 8px 0' }}>{RULE}</div>
                        <div className="ca-modal-grid">
                            {(['master', 'investor', 'phone_pwd'] as const).map((k) => (
                                <div className="wb-settings-row" key={k}>
                                    <label>{k === 'master' ? 'Master' : k === 'investor' ? 'Investor' : 'Phone'}</label>
                                    <div className="ca-clientsearch">
                                        <input className="adm-input" type="password" value={f[k]} onChange={(e) => set({ [k]: e.target.value } as any)} />
                                        <button type="button" className="wb-btn secondary" onClick={() => set({ [k]: generatePassword() } as any)}>
                                            Generate
                                        </button>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
                <div className="adm-modal-footer">
                    <button type="button" className="wb-btn secondary" onClick={() => onError('Backend gap: New Client from account data is not exposed by the API yet.', true)}>
                        <i className="codicon codicon-organization" /> New Client
                    </button>
                    <span style={{ flex: 1 }} />
                    <button type="button" className="wb-btn secondary" onClick={onClose}>Cancel</button>
                    <button type="submit" className="wb-btn" disabled={saving}>{saving ? 'Creating…' : 'OK'}</button>
                </div>
            </form>
        </FloatingWindow>
    );
}
